# Generated by Django 3.2.5 on 2021-09-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destiny_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('ratings', models.CharField(max_length=5)),
                ('reviews', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=25)),
                ('long_desc', models.CharField(max_length=2000)),
                ('img1', models.CharField(max_length=10)),
                ('img2', models.CharField(max_length=10)),
                ('img3', models.CharField(max_length=10)),
                ('img4', models.CharField(max_length=10)),
                ('img5', models.CharField(max_length=10)),
            ],
        ),
    ]
