# Generated by Django 3.2.5 on 2021-09-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0003_auto_20210910_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destiny_model',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='destiny_model',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='destiny_model',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='destiny_model',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='destiny_model',
            name='img5',
        ),
    ]
