# Generated by Django 3.2.5 on 2021-09-10 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0004_auto_20210910_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='destiny_model',
            name='img1',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
