# Generated by Django 3.2.5 on 2021-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0005_destiny_model_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny_model',
            name='short_desc',
            field=models.CharField(max_length=20),
        ),
    ]
