# Generated by Django 3.2.5 on 2021-09-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0006_alter_destiny_model_short_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destiny_model',
            new_name='Destiny',
        ),
    ]
