# Generated by Django 3.2.5 on 2021-09-17 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0007_rename_destiny_model_destiny'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destiny',
            old_name='img1',
            new_name='img_name',
        ),
        migrations.AddField(
            model_name='destiny',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destiny',
            name='long_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destiny',
            name='short_desc',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='destiny',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
