# Generated by Django 3.2.5 on 2021-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0008_auto_20210917_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destiny',
            name='long_desc',
            field=models.CharField(max_length=12000),
        ),
        migrations.AlterField(
            model_name='destiny',
            name='short_desc',
            field=models.CharField(max_length=300),
        ),
    ]
