# Generated by Django 3.2.5 on 2021-09-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
                ('cc', models.CharField(max_length=10)),
                ('milleage', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=300)),
                ('img_name', models.CharField(max_length=20)),
            ],
        ),
    ]
